In [12]:
import pandas as pd
print("Pandas 版本:", pd.__version__)

Pandas 版本: 3.0.1

In [13]:
#建立練習用的模擬台股資料表
data={
    "股票代號": ["2330", "2317", "2454", "1301", "2882"],
      "公司名稱": ["台積電", "鴻海", "聯發科", "台塑", "國泰金"],
      "收盤價": [895, 178, 1320, 68.5, 52.3],
      "成交量(張)": [45230, 32100, 8750, 12400, 18900],
      "產業": ["半導體", "電子代工", "半導體", "塑化", "金融"]
      }
df=pd.DataFrame(data)
df

   股票代號 公司名稱     收盤價  成交量(張)    產業
0  2330  台積電   895.0   45230   半導體
1  2317   鴻海   178.0   32100  電子代工
2  2454  聯發科  1320.0    8750   半導體
3  1301   台塑    68.5   12400    塑化
4  2882  國泰金    52.3   18900    金融

In [14]:
#學習操作panda表格之，只看前三筆資料
df.head(3)

   股票代號 公司名稱     收盤價  成交量(張)    產業
0  2330  台積電   895.0   45230   半導體
1  2317   鴻海   178.0   32100  電子代工
2  2454  聯發科  1320.0    8750   半導體

In [15]:
#學習操作panda表格之，只看特定資料
df[df["產業"]=="半導體"]

   股票代號 公司名稱     收盤價  成交量(張)   產業
0  2330  台積電   895.0   45230  半導體
2  2454  聯發科  1320.0    8750  半導體

In [16]:
#學習操作panda表格之，排序(從大到小)
df.sort_values("收盤價",ascending=False)

   股票代號 公司名稱     收盤價  成交量(張)    產業
2  2454  聯發科  1320.0    8750   半導體
0  2330  台積電   895.0   45230   半導體
1  2317   鴻海   178.0   32100  電子代工
3  1301   台塑    68.5   12400    塑化
4  2882  國泰金    52.3   18900    金融

In [17]:
#學習操作panda表格之，只看特定資料之特定欄位
df[["公司名稱","收盤價"]]

  公司名稱     收盤價
0  台積電   895.0
1   鴻海   178.0
2  聯發科  1320.0
3   台塑    68.5
4  國泰金    52.3

In [18]:
#學習操作panda表格之，簡單的統計相關公式
print("平均收盤價：", df["收盤價"].mean())
print("最高收盤價：", df["收盤價"].max())
print("最低收盤價：", df["收盤價"].min())
print("總成交量：", df["成交量(張)"].sum())

平均收盤價： 502.76000000000005
最高收盤價： 1320.0
最低收盤價： 52.3
總成交量： 117380

In [19]:
#學習操作panda表格之，分組統計 groupby:按產業分組，計算每個產業的平均收盤價
df.groupby("產業")["收盤價"].mean()

產業
半導體     1107.5
塑化        68.5
金融        52.3
電子代工     178.0
Name: 收盤價, dtype: float64

In [20]:
#學習操作panda表格之，新增欄位：每張收盤價（收盤價 / 1000 股
df["每張價值(元)"]=df["收盤價"]*1000
df

   股票代號 公司名稱     收盤價  成交量(張)    產業    每張價值(元)
0  2330  台積電   895.0   45230   半導體   895000.0
1  2317   鴻海   178.0   32100  電子代工   178000.0
2  2454  聯發科  1320.0    8750   半導體  1320000.0
3  1301   台塑    68.5   12400    塑化    68500.0
4  2882  國泰金    52.3   18900    金融    52300.0

In [21]:
#學習操作panda表格之，把我的表格存成 CSV 檔
df.to_csv("practice_data/sample_stock.csv",index=False,encoding="utf-8-sig")
print("File saved!")

File saved!

In [22]:
#檢查Notebook位置
import os
print(os.getcwd())

c:\projects\finance-ai-project\notebooks

In [23]:
#學習操作panda表格之，讀取CSV檔的資料
df2=pd.read_csv("practice_data/sample_stock.csv")
print("資料筆數:",len(df2))
print("欄位名稱:",list(df2.columns))

資料筆數: 5
欄位名稱: ['股票代號', '公司名稱', '收盤價', '成交量(張)', '產業', '每張價值(元)']

In [ ]:
#刪除欄位
df=df.drop("每股價值(元)",axis=1)
df

In [25]:
#練習merge(合併表格)，先建一個模擬的法人買賣超表格
chips_data={
    "股票代號":["2330","2317","2454","1301","2882"],
    "外資買賣超(張)": [12500, -8700, 3200, -1500, 6800],
    "投信買賣超(張)": [800, 200, 1500, -300, 400]
}
chips_df=pd.DataFrame(chips_data)
chips_df

   股票代號  外資買賣超(張)  投信買賣超(張)
0  2330     12500       800
1  2317     -8700       200
2  2454      3200      1500
3  1301     -1500      -300
4  2882      6800       400

In [ ]:
#練習merge(合併表格)，將模擬台股資料表和模擬法人買賣超合併
merged_df=pd.merge(df,chips_df,on="股票代號")
merged_df

   股票代號 公司名稱     收盤價  成交量(張)    產業    每張價值(元)  外資買賣超(張)  投信買賣超(張)
0  2330  台積電   895.0   45230   半導體   895000.0     12500       800
1  2317   鴻海   178.0   32100  電子代工   178000.0     -8700       200
2  2454  聯發科  1320.0    8750   半導體  1320000.0      3200      1500
3  1301   台塑    68.5   12400    塑化    68500.0     -1500      -300
4  2882  國泰金    52.3   18900    金融    52300.0      6800       400

In [26]:
import requests

In [27]:
# 用一個免費的公開 API 來練習
response=requests.get("https://api.exchangerate-api.com/v4/latest/USD")
print("狀態碼",response.status_code)
print("資料類型",type(response.json()))

狀態碼 200
資料類型 <class 'dict'>

In [28]:
# 取出免費api的匯率資料
data=response.json()
twd_rate=data["rates"]["TWD"]
jpy_rate=data["rates"]["JPY"]

print("1美元=",twd_rate,"台幣")
print("1美元=",jpy_rate,"日圓")

1美元= 32.02 台幣
1美元= 158.65 日圓

In [29]:
#把匯率API資料轉成 DataFrame
exchange_data=response.json()
rates_df=pd.DataFrame(
    list(exchange_data["rates"].items()),
    columns=["貨幣","匯率"]
)
rates_df.head(10)

    貨幣       匯率
0  USD     1.00
1  AED     3.67
2  AFN    64.59
3  ALL    82.71
4  AMD   377.29
5  ANG     1.79
6  AOA   921.01
7  ARS  1387.72
8  AUD     1.44
9  AWG     1.79

In [30]:
# 練習操作表格
twd=rates_df[rates_df["貨幣"]=="TWD"]
print("台幣匯率",twd["匯率"].values[0])
print("\n匯率最高的5個貨幣:")
rates_df.sort_values("匯率",ascending=False).head(5)

台幣匯率 32.02

匯率最高的5個貨幣:

      貨幣          匯率
68   IRR  1077735.88
84   LBP    89500.00
152  VND    26212.61
130  SLL    24661.73
83   LAK    21976.55

In [31]:
# 進階練習，從匯率表中篩選出亞洲主要貨幣
#ac=asain currencies
ac=["TWD","JPY","KRW","CNY","HKD","SGD"]
asian_rates=rates_df[rates_df["貨幣"].isin(ac)].sort_values("匯率",ascending=False)
asian_rates

      貨幣       匯率
79   KRW  1510.45
73   JPY   158.65
145  TWD    32.02
58   HKD     7.84
32   CNY     6.89
127  SGD     1.28

In [32]:
# 綜合練習把 Pandas 和 API 串在一起：幫台股資料加上美元計價
twd_rate=rates_df[rates_df["貨幣"]=="TWD"]["匯率"].values[0]
df["美元計價"]=(df["收盤價"]/twd_rate).round(2)
df[["公司名稱","收盤價","美元計價"]]

  公司名稱     收盤價   美元計價
0  台積電   895.0  27.95
1   鴻海   178.0   5.56
2  聯發科  1320.0  41.22
3   台塑    68.5   2.14
4  國泰金    52.3   1.63